# Generated by Django 5.0 on 2023-12-15 22:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='table_User_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_session', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 12, 15, 19, 37, 30, 265453))),
                ('fecha_modificacion', models.DateTimeField(default=datetime.datetime(2023, 12, 15, 19, 37, 30, 265453))),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Data',
            },
        ),
        migrations.CreateModel(
            name='table_Respuestas_Automaticas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_file', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 12, 15, 19, 37, 30, 265453))),
                ('id_user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.table_user_data')),
            ],
            options={
                'db_table': 'Respuestas_Automaticas',
            },
        ),
    ]
