# Generated by Django 5.0 on 2023-12-16 20:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_respuestas_automaticas',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 17, 26, 499059)),
        ),
        migrations.AlterField(
            model_name='table_user_data',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 17, 26, 499059)),
        ),
        migrations.AlterField(
            model_name='table_user_data',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 17, 26, 499059)),
        ),
        migrations.CreateModel(
            name='table_CronoJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_cronojob', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('fecha_ejecusion', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 17, 26, 500035))),
                ('id_user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.table_user_data')),
            ],
            options={
                'db_table': 'CronoJobs',
            },
        ),
    ]
