# Generated by Django 5.0 on 2023-12-16 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0002_alter_table_respuestas_automaticas_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_cronojobs',
            name='name_file',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='table_cronojobs',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 44, 10, 357783)),
        ),
        migrations.AlterField(
            model_name='table_respuestas_automaticas',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 44, 10, 357783)),
        ),
        migrations.AlterField(
            model_name='table_user_data',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 44, 10, 356807)),
        ),
        migrations.AlterField(
            model_name='table_user_data',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 17, 44, 10, 356807)),
        ),
    ]
